# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-31428-lsriw/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z010clg400-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ipshared/70cf/hdl
    /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ipshared/85a3
    /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ipshared/1b7e/hdl/verilog
    /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ipshared/122e/hdl/verilog
    /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ipshared/7d3c/hdl/verilog
    /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ipshared/c45e/hdl/verilog
    /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ipshared/ec67/hdl
    /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ipshared/979d/hdl/verilog
    /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ipshared/b2d0/hdl/verilog
    /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ip/ald_dvi2rgb_0_0/src
  } {
      /opt/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /opt/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /opt/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ipshared/70cf/hdl
    /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ipshared/85a3
    /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ipshared/1b7e/hdl/verilog
    /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ipshared/122e/hdl/verilog
    /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ipshared/7d3c/hdl/verilog
    /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ipshared/c45e/hdl/verilog
    /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ipshared/ec67/hdl
    /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ipshared/979d/hdl/verilog
    /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ipshared/b2d0/hdl/verilog
    /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ip/ald_dvi2rgb_0_0/src
  } {
      ./.Xil/Vivado-31428-lsriw/realtime/ald_processing_system7_0_0_stub.v
      ./.Xil/Vivado-31428-lsriw/realtime/ald_clk_wiz_0_0_stub.v
      ./.Xil/Vivado-31428-lsriw/realtime/ald_rgb2vga_0_0_stub.v
      ./.Xil/Vivado-31428-lsriw/realtime/ald_dvi2rgb_0_0_stub.v
      ./.Xil/Vivado-31428-lsriw/realtime/ald_v_vid_in_axi4s_0_0_stub.v
      ./.Xil/Vivado-31428-lsriw/realtime/ald_v_axi4s_vid_out_0_0_stub.v
      ./.Xil/Vivado-31428-lsriw/realtime/ald_v_tc_0_0_stub.v
      ./.Xil/Vivado-31428-lsriw/realtime/ald_rst_ps7_0_100M_0_stub.v
      ./.Xil/Vivado-31428-lsriw/realtime/ald_parameter_register_0_0_stub.v
      ./.Xil/Vivado-31428-lsriw/realtime/ald_draw_bbox_0_0_stub.v
      ./.Xil/Vivado-31428-lsriw/realtime/ald_blk_mem_gen_0_0_stub.v
      ./.Xil/Vivado-31428-lsriw/realtime/ald_write_video_bram_0_0_stub.v
      ./.Xil/Vivado-31428-lsriw/realtime/ald_system_ila_0_0_stub.v
      ./.Xil/Vivado-31428-lsriw/realtime/ald_shift_reg_0_0_stub.v
      ./.Xil/Vivado-31428-lsriw/realtime/ald_xbar_1_stub.v
      ./.Xil/Vivado-31428-lsriw/realtime/ald_axi_bram_ctrl_0_3_stub.v
      ./.Xil/Vivado-31428-lsriw/realtime/ald_axi_smc_1_stub.v
      ./.Xil/Vivado-31428-lsriw/realtime/ald_shift_reg_1_0_stub.v
      ./.Xil/Vivado-31428-lsriw/realtime/ald_auto_pc_0_stub.v
      /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/hdl/ald_wrapper.v
      /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/synth/ald.v
      /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ipshared/4649/hdl/xlconstant_v1_1_vl_rfs.v
      /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ip/ald_xlconstant_0_0/synth/ald_xlconstant_0_0.v
      /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ip/ald_xlconstant_0_1/synth/ald_xlconstant_0_1.v
      /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v
      /home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ip/ald_xlconcat_0_0/synth/ald_xlconcat_0_0.v
    }
      rt::read_vhdl -lib xpm /opt/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-31428-lsriw/realtime/ald_wrapper_synth.xdc
    rt::sdcChecksum
    set rt::top ald_wrapper
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {/home/lsriw/HSVS/0404/ald_cpu_hdmi_vga/ald/ald.cache/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-31428-lsriw/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
