# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tomasz/skrypty/skrypt_psra/solution/ald/ald.srcs/sources_1/bd/ald/ip/ald_dvi2rgb_0_0/ald_dvi2rgb_0_0.xci
# IP: The module: 'ald_dvi2rgb_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tomasz/skrypty/skrypt_psra/solution/ald/ald.srcs/sources_1/bd/ald/ip/ald_dvi2rgb_0_0/src/dvi2rgb.xdc
# XDC: The top module name and the constraint reference have the same name: 'ald_dvi2rgb_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/tomasz/skrypty/skrypt_psra/solution/ald/ald.srcs/sources_1/bd/ald/ip/ald_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ald_dvi2rgb_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/tomasz/skrypty/skrypt_psra/solution/ald/ald.srcs/sources_1/bd/ald/ip/ald_dvi2rgb_0_0/ald_dvi2rgb_0_0.xci
# IP: The module: 'ald_dvi2rgb_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tomasz/skrypty/skrypt_psra/solution/ald/ald.srcs/sources_1/bd/ald/ip/ald_dvi2rgb_0_0/src/dvi2rgb.xdc
# XDC: The top module name and the constraint reference have the same name: 'ald_dvi2rgb_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/tomasz/skrypty/skrypt_psra/solution/ald/ald.srcs/sources_1/bd/ald/ip/ald_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ald_dvi2rgb_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
