# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_system_ila_0_0/ald_system_ila_0_0.xci
# IP: The module: 'ald_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_system_ila_0_0/bd_0/bd_f17d.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f17d || ORIG_REF_NAME==bd_f17d} -quiet] -quiet

# IP: /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_system_ila_0_0/bd_0/ip/ip_0/bd_f17d_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f17d_ila_lib_0 || ORIG_REF_NAME==bd_f17d_ila_lib_0} -quiet] -quiet

# XDC: /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_system_ila_0_0/ald_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ald_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f17d_ila_lib_0 || ORIG_REF_NAME==bd_f17d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f17d_ila_lib_0 || ORIG_REF_NAME==bd_f17d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_system_ila_0_0/bd_0/ip/ip_0/bd_f17d_ila_lib_0_ooc.xdc

# XDC: /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_system_ila_0_0/bd_0/bd_f17d_ooc.xdc

# IP: /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_system_ila_0_0/ald_system_ila_0_0.xci
# IP: The module: 'ald_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_system_ila_0_0/bd_0/bd_f17d.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f17d || ORIG_REF_NAME==bd_f17d} -quiet] -quiet

# IP: /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_system_ila_0_0/bd_0/ip/ip_0/bd_f17d_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f17d_ila_lib_0 || ORIG_REF_NAME==bd_f17d_ila_lib_0} -quiet] -quiet

# XDC: /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_system_ila_0_0/ald_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ald_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f17d_ila_lib_0 || ORIG_REF_NAME==bd_f17d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f17d_ila_lib_0 || ORIG_REF_NAME==bd_f17d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_system_ila_0_0/bd_0/ip/ip_0/bd_f17d_ila_lib_0_ooc.xdc

# XDC: /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_system_ila_0_0/bd_0/bd_f17d_ooc.xdc
