# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/tomasz/fpga_zynq/zybo/base_designs/draw_bbox/draw_bbox.cache/wt [current_project]
set_property parent.project_path /home/tomasz/fpga_zynq/zybo/base_designs/draw_bbox/draw_bbox.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths /home/tomasz/fpga_zynq/zybo/base_designs/draw_bbox/draw_bbox.srcs/sources_1/new [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  /home/tomasz/fpga_zynq/zybo/base_designs/draw_bbox/draw_bbox.srcs/sources_1/new/signle_bbox.v
  /home/tomasz/fpga_zynq/zybo/base_designs/draw_bbox/draw_bbox.srcs/sources_1/new/draw_bbox.v
}
synth_design -top draw_bbox -part xc7z010clg400-1
write_checkpoint -noxdef draw_bbox.dcp
catch { report_utilization -file draw_bbox_utilization_synth.rpt -pb draw_bbox_utilization_synth.pb }
