# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/lsriw/PSRA/DG/lab6/ald/ald.cache/wt [current_project]
set_property parent.project_path /home/lsriw/PSRA/DG/lab6/ald/ald.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths {
  /home/lsriw/PSRA/DG/lab6/ip_repo/parameter_register_1.0
  /home/lsriw/PSRA/DG/lab3/maciej/lab2/ip_repo
  /home/lsriw/PSRA/DG/lab6/ip_repo/draw_bbox
  /home/lsriw/PSRA/DG/lab6/write_video_bram
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/lsriw/PSRA/DG/lab6/ald/ald.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/hdl/ald_wrapper.v
add_files /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ald.bd
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_processing_system7_0_0/ald_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_dvi2rgb_0_0/src/dvi2rgb.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_v_vid_in_axi4s_0_0/ald_v_vid_in_axi4s_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_v_vid_in_axi4s_0_0/ald_v_vid_in_axi4s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_v_axi4s_vid_out_0_0/ald_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_v_axi4s_vid_out_0_0/ald_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_rst_ps7_0_100M_0/ald_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_rst_ps7_0_100M_0/ald_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_rst_ps7_0_100M_0/ald_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_v_tc_0_0_2/ald_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_v_tc_0_0_2/ald_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_clk_wiz_0_1/ald_clk_wiz_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_clk_wiz_0_1/ald_clk_wiz_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_clk_wiz_0_1/ald_clk_wiz_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_xbar_0/ald_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_axi_bram_ctrl_0_0/ald_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_blk_mem_gen_0_0/ald_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_axi_smc_0/bd_0/ip/ip_1/bd_d54d_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_axi_smc_0/bd_0/ip/ip_1/bd_d54d_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_axi_smc_0/bd_0/ip/ip_5/bd_d54d_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_axi_smc_0/bd_0/ip/ip_6/bd_d54d_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_axi_smc_0/bd_0/ip/ip_7/bd_d54d_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_axi_smc_0/bd_0/ip/ip_8/bd_d54d_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_axi_smc_0/bd_0/ip/ip_9/bd_d54d_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_axi_smc_0/bd_0/ip/ip_10/bd_d54d_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_axi_smc_0/bd_0/ip/ip_11/bd_d54d_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_system_ila_0_0/ald_system_ila_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_system_ila_0_0/bd_0/ip/ip_0/bd_f17d_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_system_ila_0_0/bd_0/bd_f17d_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ip/ald_auto_pc_0/ald_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/sources_1/bd/ald/ald_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/constrs_1/imports/hdmi_vga_zybo_src/Zybo_HDMI.xdc
set_property used_in_implementation false [get_files /home/lsriw/PSRA/DG/lab6/ald/ald.srcs/constrs_1/imports/hdmi_vga_zybo_src/Zybo_HDMI.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ald_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ald_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ald_wrapper_utilization_synth.rpt -pb ald_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
