# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/hdmi_vga_zybo_src/Zybo_HDMI.xdc

# Block Designs: bd/ald/ald.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ald || ORIG_REF_NAME==ald} -quiet] -quiet

# IP: bd/ald/ip/ald_processing_system7_0_0/ald_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ald_processing_system7_0_0 || ORIG_REF_NAME==ald_processing_system7_0_0} -quiet] -quiet

# IP: bd/ald/ip/ald_clk_wiz_0_0/ald_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ald_clk_wiz_0_0 || ORIG_REF_NAME==ald_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ald/ip/ald_rgb2vga_0_0/ald_rgb2vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ald_rgb2vga_0_0 || ORIG_REF_NAME==ald_rgb2vga_0_0} -quiet] -quiet

# IP: bd/ald/ip/ald_dvi2rgb_0_0/ald_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ald_dvi2rgb_0_0 || ORIG_REF_NAME==ald_dvi2rgb_0_0} -quiet] -quiet

# IP: bd/ald/ip/ald_xlconstant_0_0/ald_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ald_xlconstant_0_0 || ORIG_REF_NAME==ald_xlconstant_0_0} -quiet] -quiet

# IP: bd/ald/ip/ald_xlconstant_0_1/ald_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ald_xlconstant_0_1 || ORIG_REF_NAME==ald_xlconstant_0_1} -quiet] -quiet

# IP: bd/ald/ip/ald_v_vid_in_axi4s_0_0/ald_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ald_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==ald_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/ald/ip/ald_v_axi4s_vid_out_0_0/ald_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ald_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==ald_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/ald/ip/ald_v_tc_0_0/ald_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ald_v_tc_0_0 || ORIG_REF_NAME==ald_v_tc_0_0} -quiet] -quiet

# IP: bd/ald/ip/ald_rst_ps7_0_100M_0/ald_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ald_rst_ps7_0_100M_0 || ORIG_REF_NAME==ald_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/ald/ip/ald_xlconcat_0_0/ald_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ald_xlconcat_0_0 || ORIG_REF_NAME==ald_xlconcat_0_0} -quiet] -quiet

# IP: bd/ald/ip/ald_parameter_register_0_0/ald_parameter_register_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ald_parameter_register_0_0 || ORIG_REF_NAME==ald_parameter_register_0_0} -quiet] -quiet

# IP: bd/ald/ip/ald_draw_bbox_0_0/ald_draw_bbox_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ald_draw_bbox_0_0 || ORIG_REF_NAME==ald_draw_bbox_0_0} -quiet] -quiet

# IP: bd/ald/ip/ald_blk_mem_gen_0_0/ald_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ald_blk_mem_gen_0_0 || ORIG_REF_NAME==ald_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/ald/ip/ald_write_video_bram_0_0/ald_write_video_bram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ald_write_video_bram_0_0 || ORIG_REF_NAME==ald_write_video_bram_0_0} -quiet] -quiet

# IP: bd/ald/ip/ald_system_ila_0_0/ald_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ald_system_ila_0_0 || ORIG_REF_NAME==ald_system_ila_0_0} -quiet] -quiet

# IP: bd/ald/ip/ald_shift_reg_0_0/ald_shift_reg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ald_shift_reg_0_0 || ORIG_REF_NAME==ald_shift_reg_0_0} -quiet] -quiet

# IP: bd/ald/ip/ald_xbar_1/ald_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ald_xbar_1 || ORIG_REF_NAME==ald_xbar_1} -quiet] -quiet

# IP: bd/ald/ip/ald_ps7_0_axi_periph_1/ald_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ald_ps7_0_axi_periph_1 || ORIG_REF_NAME==ald_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/ald/ip/ald_axi_bram_ctrl_0_3/ald_axi_bram_ctrl_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ald_axi_bram_ctrl_0_3 || ORIG_REF_NAME==ald_axi_bram_ctrl_0_3} -quiet] -quiet

# IP: bd/ald/ip/ald_axi_smc_1/ald_axi_smc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ald_axi_smc_1 || ORIG_REF_NAME==ald_axi_smc_1} -quiet] -quiet

# IP: bd/ald/ip/ald_shift_reg_1_0/ald_shift_reg_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ald_shift_reg_1_0 || ORIG_REF_NAME==ald_shift_reg_1_0} -quiet] -quiet

# IP: bd/ald/ip/ald_auto_pc_0/ald_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ald_auto_pc_0 || ORIG_REF_NAME==ald_auto_pc_0} -quiet] -quiet

# XDC: bd/ald/ald_ooc.xdc
