# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lsriw/PSRA/DG/lab4/ald/ald.srcs/sources_1/bd/ald/ip/ald_xbar_0/ald_xbar_0.xci
# IP: The module: 'ald_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lsriw/PSRA/DG/lab4/ald/ald.srcs/sources_1/bd/ald/ip/ald_xbar_0/ald_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ald_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/lsriw/PSRA/DG/lab4/ald/ald.srcs/sources_1/bd/ald/ip/ald_xbar_0/ald_xbar_0.xci
# IP: The module: 'ald_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lsriw/PSRA/DG/lab4/ald/ald.srcs/sources_1/bd/ald/ip/ald_xbar_0/ald_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ald_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
