# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lsriw/HSVS/OgorekPiotr/7.03/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ip/ald_v_vid_in_axi4s_0_0/ald_v_vid_in_axi4s_0_0.xci
# IP: The module: 'ald_v_vid_in_axi4s_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lsriw/HSVS/OgorekPiotr/7.03/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ip/ald_v_vid_in_axi4s_0_0/ald_v_vid_in_axi4s_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ald_v_vid_in_axi4s_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/lsriw/HSVS/OgorekPiotr/7.03/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ip/ald_v_vid_in_axi4s_0_0/ald_v_vid_in_axi4s_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ald_v_vid_in_axi4s_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/lsriw/HSVS/OgorekPiotr/7.03/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ip/ald_v_vid_in_axi4s_0_0/ald_v_vid_in_axi4s_0_0.xci
# IP: The module: 'ald_v_vid_in_axi4s_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lsriw/HSVS/OgorekPiotr/7.03/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ip/ald_v_vid_in_axi4s_0_0/ald_v_vid_in_axi4s_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ald_v_vid_in_axi4s_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/lsriw/HSVS/OgorekPiotr/7.03/ald_cpu_hdmi_vga/ald/ald.srcs/sources_1/bd/ald/ip/ald_v_vid_in_axi4s_0_0/ald_v_vid_in_axi4s_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ald_v_vid_in_axi4s_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
